---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-tool-service-web
    service: das-tool-service
  name: das-tool-service-web
  namespace: {{KubernetesNamespace}}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: das-tool-service-web
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-tool-service-web
    version: {{buildNumber}}
    service: das-tool-service
  name: das-tool-service-web
  namespace: {{KubernetesNamespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-tool-service-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: das-tool-service-web
        service: das-tool-service
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        agentpool: {{toolsAgentName}}
      containers:
        - name: das-tool-service
          image: {{PublicAcrName}}.azurecr.io/das-tools-service:{{buildNumber}}
          imagePullPolicy: Always
          env:
            - name: AzureAdConfiguration__Authority
              value: https://login.microsoftonline.com/{{Tenant}}
            - name: AzureAdConfiguration__ClientId
              value: {{ToolsServiceAadOidcClientId}}
            - name: AzureAdConfiguration__ClientSecret
              value: {{ToolsServiceAadOidcClientSecret}}
            - name: DatabaseConnectionString
              value: {{DatabaseConnectionString}}
            - name: DfESigninAddress
              value: {{DfeSignInAddress}}
            - name: ASPNETCORE_URLS
              value: "http://+:80"
          envFrom:
            - configMapRef:
                name: das-tool-service-shared-config
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 512Mi
      volumes:
        - name: shared-app-settings
          configMap:
            name: das-tool-service-shared-config
